apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.id: {{ quote .Values.global.network.elbId }}
  labels:
    app: faas-frontend
  name: faas-frontend-lb
  namespace: {{ .Values.global.namespace }}
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: faas-frontend
  ports:
    - name: faas-frontend-lb
      protocol: TCP
      port: {{ .Values.global.port.faasFrontendNodePort }}
      targetPort: {{ .Values.global.port.fassFrontendPort }}
      nodePort: {{ .Values.global.port.faasFrontendNodePort }}