apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: faas-manager
rules:
  - apiGroups:
      - patservice.cap.io
    resources:
      - '*'
      - pats
    verbs:
      - '*'