[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:traefik]
command=/usr/local/bin/traefik --configFile=/openyuanrong/traefik/traefik.yml
autostart=true
autorestart=true
startretries=3
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/traefik.log
stderr_logfile=/var/log/supervisor/traefik.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
priority=10

[program:runtime-launcher]
command=/openyuanrong/runtime-launcher
autostart=true
autorestart=true
startretries=3
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/runtime-launcher.log
stderr_logfile=/var/log/supervisor/runtime-launcher.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
priority=20

[program:yuanrong-master]
command=/usr/local/bin/yr start --master --port_policy FIX --enable_faas_frontend=true --faas_frontend_http_port 8889 --enable_function_scheduler true --enable_meta_service true --ssl_base_path /openyuanrong/cert --frontend_ssl_enable true --enable_iam_server %(ENV_ENABLE_TOKEN)s --frontend_client_auth_type NoClientCert --enable_function_token_auth %(ENV_ENABLE_TOKEN)s -a 127.0.0.1 -p /openyuanrong/services.yaml
autostart=true
autorestart=true
startretries=3
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/yuanrong.log
stderr_logfile=/var/log/supervisor/yuanrong.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
priority=30
startsecs=5
environment=CONTAINER_EP="unix:///var/run/runtime-launcher.sock"
