apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.global.namespace }}
  name: curve-secret
type: Opaque
data:
  client.key_secret: "{{ .Values.global.curve.clientPrivateKey }}"
  client.key: "{{ .Values.global.curve.clientPublicKey }}"
  worker.key: "{{ .Values.global.curve.workerPublicKey }}"