apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-adaptor
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.global.replicas.iamAdaptor }}
  selector:
    matchLabels:
      app: iam-adaptor
  template:
    metadata:
      labels:
        app: iam-adaptor
    spec:
      volumes:
        - name: log-volume
          hostPath:
            path: "{{ .Values.global.log.hostPath.componentLog }}"
            type: DirectoryOrCreate
        - name: data-volume
          emptyDir:
            sizeLimit: 5Gi
      initContainers:
        - name: agent-init-container
          image: {{ .Values.global.imageRegistry }}{{ .Values.global.images.agentInit }}
          command: ["/bin/sh", "-c", "chown 1002:1002 /opt/yuanrong/logs && chmod 777 /opt/yuanrong/logs"]
          resources:
            limits:
              cpu: {{ .Values.global.resources.functionAgentInit.limits.cpu }}
              memory: {{ .Values.global.resources.functionAgentInit.limits.memory }}
            requests:
              cpu: {{ .Values.global.resources.functionAgentInit.requests.cpu }}
              memory: {{ .Values.global.resources.functionAgentInit.requests.memory }}
          volumeMounts:
            - name: log-volume
              mountPath: /opt/yuanrong/logs
              subPathExpr: $(RUNTIME_POD_NAME)
          env:
            - name: RUNTIME_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - CHOWN
                - NET_RAW
                - NET_ADMIN
                - SYS_ADMIN
                - CHOWN
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
              drop:
                - ALL
            runAsUser: 0
      containers:
        - name: service-container
          image: {{ .Values.global.imageRegistry }}{{ .Values.global.images.common }}
          command: ["/bin/sh", "-l", "/home/sn/iam-adaptor/bin/bootstrap"]
          ports:
            - containerPort: {{ .Values.global.port.iamAdapterHttpPort }}
              protocol: TCP
          env:
            - name: RUNTIME_HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: RUNTIME_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: RUNTIME_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: RUNTIME_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: RUNTIME_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: RUNTIME_POD_UID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: X_WISECLOUD_SITE
              value: aaa.bbb
            - name: X_WISECLOUD_TENANT_ID
              value: aaa.bbb
            - name: X_WISECLOUD_APPLICATION_ID
              value: aaa.bbb
            - name: X_WISECLOUD_SERVICE_ID
              value: aaa.bbb
            - name: X_WISECLOUD_ENVIRONMENT_ID
              value: a506e551a0834d1daccd7d93cb202ae4
            - name: RUNTIME_MICROSERVICE_NAME
              value: aaa.bbb
            - name: RUNTIME_MICROSERVICE_CLUSTER
              value: cn-dev-iam-adaptor
            - name: LANG
              value: en_US.UTF-8
            - name: RUNTIME_MICROSERVICE_ENVIRONMENT
              value: aaa.bbb
            - name: RUNTIME_MICROSERVICE_SERVICE_NAME
              value: aaa.bbb
            - name: RUNTIME_MICROSERVICE_BUSINESS
              value: aaa.bbb
            - name: RUNTIME_MICROSERVICE_REGION
              value: cn-north-4
            - name: RUNTIME_MICROSERVICE_AZ
              value: cn-north-4g
            - name: X_WISECLOUD_CLOUDMAP_ID
              value: aaa.bbb
            - name: NUWA_CLOUDMAP_NAMESPACENAME
              value: aaa.bbb
            - name: NUWA_CLOUDMAP_SERVERADDR
              value:
            - name: NUWA_CLOUDMAP_DUAL_SERVERADDR
              value:
            - name: TZ
              value: Asia/Shanghai
            - name: WISECLOUD_ACMS_ENDPOINT
              value: 
            - name: META_STORE_ADDRESS
              {{- if .Values.global.metaStore.enable }}
              value: "{{ .Values.global.metaStore.address }}"
              {{- else }}
              value: "{{ .Values.global.etcdManagement.metcd }}"
              {{- end }}
            - name: LOG_PATH
              value: "/opt/yuanrong/logs"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: CLUSTER_ID
              value: {{ quote .Values.global.clusterId }}
            - name: LOG_COMPRESS_ENABLE
              value: "true"
            - name: LOG_ROLLING_MAXSIZE
              value: "1000"
            - name: LOG_ROLLING_MAXFILES
              value: "3"
            - name: LOG_ASYNC_LOGBUFSECS
              value: "30"
            - name: LOG_ASYNC_MAXQUEUESIZE
              value: "51200"
            - name: LOG_ASYNC_THREADCOUNT
              value: "1"
            - name: LOG_ALSOLOGTOSTDERR
              value: "false"
            - name: DECRYPT_ALGORITHM
              value: "{{ .Values.global.common.decryptAlgorithm }}"
            - name: TOKEN_EXPIRED_TIME_SPAN
              value: "{{ .Values.global.iam.tokenExpiredTimeSpan }}"
            - name: IAM_LISTEN_PORT
              value: "{{ .Values.global.port.iamAdapterHttpPort }}"
            - name: ENABLE_IAM
              value: "{{ .Values.global.iam.enable }}"
            - name: IAM_CREDENTIAL_TYPE
              value: "{{ .Values.global.iam.credentialType }}"
            - name: CREDENTIAL_HOST_ADDRESS
              value: ""
            - name: MAX_STORAGE_OPERATE_RETRY_TIMES
              value: "60"
            - name: SYSTEM_AUTH_MODE
              value: "{{ .Values.global.common.systemAuthMode }}"
            - name: SSL_ENABLE
              value: "{{ .Values.global.mutualSSLConfig.sslEnable }}"
            - name: RESOURCE_PATH
              value: "/home/sn/resource"
            - name: SCC_ENABLE
              value: "{{ .Values.global.scc.enable }}"
            - name: SCC_ALGORITHM
              value: "AES256_GCM"
            - name: ETCD_AUTH_TYPE
              value: "{{ .Values.global.etcdManagement.authType }}"
            - name: K8S_BASE_URL
              value: "{{ .Values.global.kubernetes.kubeApiBaseUrl }}"
            - name: K8S_NAMESPACE
              value: "default"
            - name: MAX_TOLERATE_META_STORE_FAILED_TIMES
              value: "{{ .Values.global.etcdManagement.maxTolerateMetaStoreFailedTimes }}"
            - name: META_HEALTH_CHECK_INTERVAL_MS
              value: "{{ .Values.global.etcdManagement.metaStoreCheckHealthIntervalMs }}"
            - name: META_HEALTH_CHECK_TIMEOUTS
              value: "{{ .Values.global.etcdManagement.metaStoreTimeoutMs }}"
            - name: ELECTION_MODE
              value: "{{ .Values.global.common.electionMode }}"
            - name: ETCD_TARGET_NAME_OVERRIDE
              value: "aaa.bbb"
            - name: PERMANENT_CREDENTIAL_CONFIG_PATH
              value: "/home/sn/permanent-credential-config.json"
            - name: LOG_PATTERN
              value: '{
                      "separator": " | ",
                      "placeholders": [
                        {"flags": "%Y-%m-%dT%H:%M:%S.%f"},
                        {"flags": "%l"},
                        {"flags": "%s:%#"},
                        {"env": "POD_NAME"},
                        {"env": "CLUSTER_ID"},
                        {"flags": ""}
                      ]
                  }'
            - name: STS_CONFIG
              value: "{}"
          resources:
            limits:
              cpu: {{ .Values.global.resources.iamAdapter.limits.cpu }}
              memory: {{ .Values.global.resources.iamAdapter.limits.memory }}
            requests:
              cpu: {{ .Values.global.resources.iamAdapter.requests.cpu }}
              memory: {{ .Values.global.resources.iamAdapter.requests.memory }}
          volumeMounts:
            - name: log-volume
              mountPath: /opt/yuanrong/logs
              subPathExpr: $(RUNTIME_POD_NAME)
            - name: data-volume
              mountPath: /opt/yuanrong/data
          livenessProbe:
            tcpSocket:
              port: {{ .Values.global.port.iamAdapterHttpPort }}
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.global.port.iamAdapterHttpPort }}
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1002
            runAsNonRoot: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 300
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: {{ .Values.global.runtime.fsGroup }}
      imagePullSecrets:
        - name: default-secret
      schedulerName: default-scheduler