apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: default
data:
  config.json: |-
    {
      "authenticationEnable": false,
      "enableHealthCheck": true,
      "functionCapability": 1,
      "leaseRenewMinute": 5,
      "httpsEnable": false,
      "routerEtcd": {
        "servers": ["{{ .Values.global.etcdManagement.detcd }}"],
        {{- if eq .Values.global.etcdManagement.authType "TLS" }}
        "sslEnable": true,
        {{- else }}
        "sslEnable": false,
        {{- end}}
        "user":"",
        "password":"",
        "authType": {{ quote .Values.global.etcdManagement.authType }},
        "useSecret": {{ .Values.global.etcdManagement.useSecret }},
        "secretName": {{ quote .Values.global.etcdManagement.secretName }}
      },
      "metaEtcd": {
        "servers": ["{{ .Values.global.etcdManagement.detcd }}"],
        {{- if eq .Values.global.etcdManagement.authType "TLS" }}
        "sslEnable": true,
        {{- else }}
        "sslEnable": false,
        {{- end}}
        "user":"",
        "password":"",
        "authType": {{ quote .Values.global.etcdManagement.authType }},
        "useSecret": {{ .Values.global.etcdManagement.useSecret }},
        "secretName": {{ quote .Values.global.etcdManagement.secretName }}
      },
      "sccConfig": {
        "enable": {{ .Values.global.scc.enable }},
        "secretName": {{ quote .Values.global.scc.secretName }},
        "algorithm": {{ quote .Values.global.scc.algorithm }}
      },
      "alarmConfig": {
        "enableAlarm": false,
        "minInsStartInterval": 15,
        "minInsCheckInterval": 15,
        "alarmLogConfig": {
          "filepath": "/opt/yuanrong/logs/alarms",
          "level": "Info",
          "tick": 0,
          "first": 0,
          "thereafter": 0,
          "singlesize": 500,
          "threshold": 3,
          "disable": false
        },
        "xiangYunFourConfig": {
          "site": "aaa.bbb",
          "tenantID": "T014",
          "applicationID": "aaa.bbb",
          "serviceID": "aaa.bbb"
        }
      }
    }